# -*- coding: utf-8 -*-
"""pytorch_00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLJclYnzyJDjlervhImqAp2bmKjDBec3

## Pytorch 00
"""

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to tensors

#Scalar tensor
scalar = torch.tensor(7)
scalar

scalar.item()

scalar.ndim #ndim = n dimensions

#Vector
vector = torch.tensor([7,8])
vector

vector.shape

# Matrix 2 dimentional vector
MATRIX = torch.tensor([[2,3],[4,5]])
MATRIX

MATRIX.ndim

MATRIX[1,0]

MATRIX.shape

#TENSOR n dimensional matrix
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

TENSOR.ndim

TENSOR.shape # 1 3x3 tensor

## Random tensors
##Create a random tensor of size (3,4)

random_tansor = torch.rand(3,4)
random_tansor

random_tansor.ndim

##Create a random tensor similar to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) #Height width, color(RGB)
random_image_tensor.shape, random_image_tensor.ndim

#Binary tensor
zeros = torch.zeros(3,4)
zeros

zeros*random_tansor

ones = torch.ones(3,4)
ones

ones.dtype

#Create a range of tensors
range_tensor = torch.arange(3,10,2) #start, end, step
range_tensor

#Creating tensor like
copy_of_range_zeros = torch.zeros_like(range_tensor) #Ayni tensorun sifirlisi
copy_of_range_zeros

#Tensor Datatypes
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None, #GPU,cuda etc
                               requires_grad=False)
float_32_tensor

float_32_tensor.dtype

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

float_16_tensor*float_32_tensor

#Type of the product
(float_16_tensor*float_32_tensor).dtype

#Get information from tensors

some_tensor = torch.rand(3,4)
some_tensor

#Find the details
print(some_tensor)
print(f"Shape of tensor is {some_tensor.shape}")
print(f"Data type is {some_tensor.dtype}")
print(f"Data device is {some_tensor.device}")

#Manipulating tensors

#Addition/Substraction
tensor = torch.tensor([1,2,3])
print(tensor + 10)

#Multiply
print(tensor * 10)

# Commented out IPython magic to ensure Python compatibility.
# #Matrix Multiplication(dot product)
# %%time
# first_t = torch.tensor([[1,2,3],[2,3,4]])
# second_t = torch.tensor([[1,5,6],[1,4,5],[1,5,2]])
# 
# torch.matmul(first_t,second_t) #2x3 . 3x3 = 2x3 # "@" sembolu de kullanilabilir

#Transpose
tensor = torch.rand(2,3)
print(tensor)
print(tensor.shape)
print()

print(f"The transpose of it is: {tensor.T}")
print(tensor.T.shape)

#Find min max

x = torch.arange(1,100,10)
x, x.dtype

print(torch.min(x)) #or could use x.min()
print(x.max())
#print(torch.max(x))
print(torch.mean(x.type(torch.float32))) #64 ile calismiyor
print(torch.sum(x.type(torch.float32)))

#Find psoition of min max
print(x.argmin())
print(x.argmax())

#Reshaping, view , stacking squeezing, unsqueezing, permute
x = torch.arange(1.,11.)
x, x.shape

#Add extra dimension (Reshaping)

x_reshaped = x.reshape(1,10) #Burda 1D olan tensoru 2Dye geciriyoruz
print(x_reshaped, x.shape)
print()
x_reshaped = x.reshape(10,1)
print(x_reshaped, x.shape)

#Reshaping

x_reshaped = x.reshape(5,2) #10luk veriyi 2li paketledim burda veri saisi tuttugu icin bunu yapabiliyorum
x_reshaped

#View
z = x.view(1,10)

#Changing z changes x "hardcopy"
z = x.reshape(5,2)
z[:,0] = 5
x

#Stack
print(x)

x_stacked = torch.stack([x,x,x], dim=0) #Ust uste koy
print(x_stacked)
print()
x_stacked = torch.stack([x,x,x], dim=1) #Yan yana koy
print(x_stacked)

#Squeeze
x_reshaped = x.reshape(1,10)

print(x_reshaped)
print(x_reshaped.shape)
print()
x_squeezed = x_reshaped.squeeze()
print(x_squeezed)
print(x_squeezed.shape)

#Unsqueeze

print(x_squeezed)
print(x_squeezed.shape)
print()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed)
print(x_unsqueezed.shape)
print()
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed)
print(x_unsqueezed.shape)

#Permute - rearrange the dimensions of a target tensor in a specific order

x_image = torch.rand((224,220,3)) #Height, width, color channels

#Permute the tensor as color, height, width
x_permuted = x_image.permute(2,0,1) #Ilk hangisi gelsin seklinde calisiyo
x_permuted.shape

#Permuted view kullaniyo yani hardcopy, bi degeri degistirirsen hardcopyden de degisir

x_image[0,0,0] = 10
print(f"First element of x_image changed to {x_image[0,0,0]}")
print(f"So the x_permuted first element also changed to {x_permuted[0,0,0]}")

#Indexing
x = torch.arange(1,10).reshape(1,3,3)  #3 dimension
print(f"x is: {x} with size {x.shape}")

x[0]

#x[0,1] or
x[0][1]

x[0,1,2]

# Use : to select all colomnn
print(f"Selecting the first elements: {x[0,:,0]}")

#Get all values of 0th and 1st dimensions but only index 1 of second dim
x[:,:,1]

# Pytorch tensors ad Numpy
import torch
import numpy as np

array = np.arange(1.0,8.0)
#Changing numpy to tensor
tensor = torch.from_numpy(array)#.type(torch.float32) for default
array, tensor
#Note: It changes to float64 which is not the default in pytorch

#Change in the array reflects to the tensor "Hardcopy"
array[0] = 5
array, tensor

#Change tensor to numpy

tensor = torch.randint(0,10,(2,5))
print(tensor)

numpy_tensor = tensor.numpy()
print(numpy_tensor)

tensor[0,0] = 10
print(tensor)
print("It also changes the numpy")
print(numpy_tensor)

# Reproducibility - seed in randomness

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)
print(random_tensor_A)
torch.manual_seed(RANDOM_SEED) #Her seferide ayarlaman lazim
random_tensor_B = torch.rand(3,4)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

#!nvidia-smi

# Check for GPU access
torch.cuda.is_available()

# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Putting tensors on the GPU

tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# Move tensors back to cpu, Numpy cant run on GPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu, tensor_on_cpu.device